### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by RobAustin**
added  <a href="https://github.com/OpenHFT/Chronicle-Wire">Chronicle-Wire</a> <span class="yaml_comment">Java Implementation</span>

### CODE REVIEW

**Comment by perlpunk** [comment]
Is this a library using an existing YAML library, or does it implement YAML itself?

**Comment by RobAustin** [comment]
It implements YAML it’s self.

**Comment by perlpunk** [comment]
And which YAML version and schema does it implement?

**Comment by RobAustin** [comment]
see https://github.com/OpenHFT/Chronicle-Wire/blob/master/YAML2SpecificationCompliance.adoc

**Comment by perlpunk** [comment]
Please note that there is no YAML version 2, it's 1.2 ;-)
So maybe you should update that.

I'm currently trying to make the list of libraries more useful.
I updated the [Contributing](https://github.com/yaml/www.yaml.org/blob/gh-pages/Contributing.md) file.
So it would be useful to know about the testsuite, and which Schema it is implementing (if any).
Maybe consider to use the official YML Test Suite.

**Comment by ingydotnet** [comment]
Applied. Published. Thanks.

**Pull request closed without merging**
