### PR TITLE
Added reference to Neslib.Yaml library for Delphi

### PR DESCRIPTION
**Pull request by neslib**
Added a libyaml binding for the Delphi programming language

### CODE REVIEW

**Comment by perlpunk** [comment]
@ingydotnet this PR targets master, but we need gh-pages. Why can't we set the default branch to gh-pages?

@neslib  could you retarget your PR to gh-pages?

**Comment by neslib** [comment]
@perlpunk The [documentation ](https://github.com/yaml/www.yaml.org/blob/master/Contributing.md) says I should update the files in the `src` directory (in the Master branch), so that is what I did. Are you sure we need to target gh-pages?

**Comment by perlpunk** [comment]
@neslib Yeah, the documentation is theoretically correct, but we first need to fix the process of generating gh-pages. AFAIK it's out of sync.
Until then, we edit gh-pages by hand.
Maybe I should add that to the documentation.

**Comment by neslib** [comment]
Added a new pull request (#51) that targets the gh-pages branch

**Pull request closed without merging**
