### PR TITLE
camel java library added

### PR DESCRIPTION
**Pull request by amihaiemil**
Added link to [camel](https://github.com/decorators-squad/camel/), a new Java library for Yaml

### CODE REVIEW

**Comment by amihaiemil** [comment]
@ingy Here is the PR for camel :D

**Comment by amihaiemil** [comment]
@ingydotnet ping - can we merge this? :)

**Comment by perlpunk** [comment]
Maybe it should be added that it targets YAML 1.2?

**Comment by perlpunk** [comment]
Had to make a new PR #28 because gh-pages is currently not built from master

**Comment by ingydotnet** [comment]
Applied in #28

**Pull request closed without merging**
