### PR TITLE
Add links to Gulp-YAML (Gulp plugin for JS-YAML)

### PR DESCRIPTION
**Pull request by ehmicky**
Add links to [`gulp-yaml`](https://github.com/crissdev/gulp-yaml) which is the Gulp plugin for `js-yaml`.

### CODE REVIEW

**Comment by ehmicky** [comment]
It's a tool that converts YAML files to JSON files.

**Comment by perlpunk** [comment]
@ehmicky is it a YAML processor or just a tool for converting formats?

**Comment by ehmicky** [comment]
It processes YAML using `js-yaml` (which is a YAML processor) then stringifies it to JSON.

**Comment by ingydotnet** [comment]
Taking a pass on this one.

**Pull request closed without merging**
