### PR TITLE
Add Crystals YAML in the Projects list

### PR DESCRIPTION
**Pull request by r00ster91**
This adds the YAML library from Crystal to the projects list.
https://crystal-lang.org/api/latest/YAML.html

### CODE REVIEW

**Comment by perlpunk** [comment]
Maybe it should be added that it targets YAML 1.1? @ingydotnet thoughts?

**Comment by r00ster91** [comment]
Ok I added it

**Comment by perlpunk** [comment]
Had to make a new PR #28 because gh-pages is currently not built from master

**Comment by r00ster91** [comment]
Alright

**Pull request closed without merging**
