### PR TITLE
Add link to github.com/goccy/go-yaml for the Go language

### PR DESCRIPTION
**Pull request by goccy**
Add link to a new library ( https://github.com/goccy/go-yaml ) for the Go language

### CODE REVIEW

**Comment by goccy** [comment]
Please review this PR ... !! 🙇 ( @perlpunk )

**Comment by perlpunk** [comment]
Thanks!
I'm currently trying to make the library list more useful.
Can you please have a look at the updated [Contributing](https://github.com/yaml/www.yaml.org/blob/gh-pages/Contributing.md) file?
It would be good to know which YAML version you implement, if you support resolving of booleans etc,. and which testsuite you are using.
Is this a complete new implementation or does it use https://github.com/go-yaml/yaml under the hood?

Also I did a major update of the index.html for easier editing, so it's conflicting now. Can you update/rebase your PR?

**Comment by goccy** [comment]
@perlpunk

Thanks for the feedback !
I resolved conflicting.

This library implements from scratch ( no dependent on https://github.com/go-yaml/yaml ) .
And all features are better than go-yaml/yaml :)

Also, this implements YAML 1.2 and test in my original test cases ( covered test cases of go-yaml/yaml )

**Comment by perlpunk** [comment]
thanks, merged!

**Pull request merged**
