### PR TITLE
Updates the structure, the links and added yaml2html.pl

### PR DESCRIPTION
**Pull request by nowox**
As the YAML.org webpage looks like a YAML page. It is worth to make it
a real YAML. What I did is:
- Remove the dead links
- Review the general structure of the page
- Find a way to add hyperlinks on the YAML file (markdown format)
- Write a Perl script that generates index.html from index.yml
- Add a make rule `make html`

### CODE REVIEW

**Comment by ixti** [comment]
That is HUGE!
/cc @ingydotnet

**Comment by nowox** [comment]
They are lots of things to improve. For example the readability is less good than before because the description of the hyperlinks are not vertically aligned. I also thought to make the structure foldable using jQuery and add an outline on the right side of the page. However, I think this could be against the philosophy which is to be as simple as possible and as close as possible to a YAML file.

**Comment by nowox** [comment]
?

**Comment by Qix-** [comment]
1. Would you rebase?
2. Perhaps show a screenshot of the before/after?

Might help get this accepted :)

**Comment by adamvoss** [comment]
@nowox Cool to see this done!  I was thinking of the same think but going to use Jekyll because that is what GitHub Pages uses.  I don't know Perl, but couldn't you do an additional iteration to get the maximum width from the items, then subtract from that value to know how many spaces to add later?

**Comment by ingydotnet** [comment]
Apologies for extremely late response.
Just started a big refactoring of yaml.org, get rid of years of cruft.

I'm going to close this, but at least I need to check for bad links.
If you want to circle back on any of this let me know.

BTW, we have a new way to chat about these things.
Just stop by: https://matrix.to/#/#chat:yaml.io

**Pull request closed without merging**
