### PR TITLE
updated the Camel Java project

### PR DESCRIPTION
**Pull request by amihaiemil**
Hi @perlpunk 

I have updated the name and description of what was the previous "Camel" Java project.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@perlpunk done, thanks :)

**Comment by perlpunk** [comment]
Thanks, merged!

**Comment by perlpunk** [comment]
Btw, I don't see anything in the README about the implemented schema.
Does it implement the 1.2 Core Schema by default?
I see an example in the wiki
https://github.com/decorators-squad/eo-yaml/wiki/Convenience-Type-Casting-Methods
that has a timestamp, which is not part of the Core schema.

Could you add information about that in the README?

**Comment by amihaiemil** [comment]
@perlpunk I'm not sure what a schema is :D 
We tried to follow the 1.2 Spec Document, that's all.

**Comment by perlpunk** [comment]
Here are the Schemas for 1.2 and types for 1.1: https://perlpunk.github.io/yaml-test-schema/schemas.html

The resolving of booleans, integers and floats changed substantially, and for example timestamps and other types are explictly not in the default, so for example those should be optional.
You can also find test data under that link.
Not sure if I asked that before, but are you using (or considering using) the [yaml-test-suite](https://github.com/yaml/yaml-test-suite)?
Maybe you are also interested in adding eo-yaml to [yaml-runtimes](https://github.com/yaml/yaml-runtimes), which is the base for the [yaml-test-matrix](https://matrix.yaml.io/)?

(I'm trying to get the several libs listed on yaml.org to add more information about these things, because the list of libs is growing, and it doesn't make the decision easier which lib one wants or has to use without this important information at one glance)

**Comment by amihaiemil** [comment]
@perlpunk I will have a look over the test suite, we could add those test cases to eo-yaml, I think :) 

About the YAML types. eo-yaml doesn't really care about formal types - it doesn't "resolve" values, it just reads Strings and offers some convenience type-casting methods which will fail (e.g. NumberFormatException if the string is not a number) if the casting can't be performed.

**Comment by amihaiemil** [comment]
@perlpunk the test matrix is also a good idea, I'll have a look into it

**Comment by perlpunk** [comment]
Ah ok, so the resolving is optional and not done by eo-yaml, but by the user of the lib?
That's also important information that could be added to the homepage :)

**Comment by amihaiemil** [comment]
@perlpunk Yes, I think you could say it's done by the user. Here is reading a ``YamlMapping``:

```java
YamlMapping team = Yaml.createYamlInput(
    new File("team.yml")
).readYamlMapping();
String architect = team.string("architect");
```
So the ``architect`` plain scalar is being read (i.e. resolved) only when ``team.string("architect")`` is being called. 

But I don't really understand why this is important information? Is this behaviour important from YAML's perspective? Would it make any difference if we resolved all the values at reading time (i.e. right when ``readYamlMapping()`` is called)?

**Comment by perlpunk** [comment]
Yes, the resolving is part of reading and writing YAML documents.
If eo-yaml doesn't do that itself and only loads strings, then it's implementing the [YAML 1.2 Failsafe](https://yaml.org/spec/1.2/spec.html#id2802346) schema, so you could add that information.

I think I might want to add such basic information to the list here as well.

I'm currently updating the Contributing.md.

**Pull request merged**
